gui:
  showIcons: true
  showRandomTip: false
  showCommandLog: false
  sidePanelWidth: 0.3
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --color=always --oneline {{branchName}} --"

os:
  editPreset: vim

confirmOnQuit: false

keybinding:
  universal:
    quit: q
    return: <esc>
